language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - pytest
  - mypy -p colonel
notifications:
  webhooks: 
    - https://fathomless-fjord-24024.herokuapp.com/notify
