name: Pringles

on: [push]

jobs:
  build:
    name: Pringles latest-commit build job
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Install bison for CD++ compilation
      run: sudo apt-get install bison
    - name: Run main make script
      run: |
        make install 
        make remote
